### ISSUE TITLE
Add teacher feature in school

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [Vowel-Learning/vam-marketplace-react#14]

**Comment by sudo-NithishKarthik** [comment]
<img width="1368" alt="Screenshot 2021-04-07 at 11 21 28 @bajaj99prashant M" src="https://user-images.githubusercontent.com/75248557/113817098-6a0aa000-9793-11eb-8d22-afce6d58c438.png">
@bajaj99prashant , the button should open a modal with a form in it and takes the teacher details and send a post request to _
POST /v1/school/create-teacher/_

**Comment by bajaj99prashant** [comment]
@sudo-NithishKarthik 
What all fields are required to be present in the form inside the modal?

**Comment by sudo-NithishKarthik** [comment]
http://api.vamschool.in/api-docs/#v1-school-create-teacher-create

**Comment by bajaj99prashant** [comment]
In this endpoint email and phone wasn't necessary, but when I am sending a request the error displays for the email and phone field. When I am sending email and phone fields error is still showing.

**Comment by sudo-NithishKarthik** [comment]
In what format are you sending the data?

**Comment by sudo-NithishKarthik** [comment]
<img width="736" alt="Screenshot 2021-04-07 at 1 38 45 PM" src="https://user-images.githubusercontent.com/75248557/113832814-967be780-97a6-11eb-9b20-63f29e046873.png">


Refer these..these fields should be sent and it should work fine

**Comment by bajaj99prashant** [comment]
const dataObject = {
        email: teacher.email,
        school_name: teacher.school,
        school_about: teacher.about,
        phone: teacher.phone,
        teacher: teacher.teacherName,
      };

      createTeacher(dataObject)
        .then((data) => console.log("data ", data))
        .catch((err) => console.log("error ", err));

**Comment by bajaj99prashant** [comment]
sending like this. It says email field should not be null

**Comment by bajaj99prashant** [comment]
There is an issue in my state. I think there isn't a problem with api.

**Comment by sudo-NithishKarthik** [comment]
yes..api is fine
check whether the states are managed correctly

**Comment by bajaj99prashant** [comment]
Yeah the functionality is completed.

**Comment by sudo-NithishKarthik** [comment]
Great  🙌
Push the recent code
