### ISSUE TITLE
Uneven ordering in upload subjects page (school)

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [Vowel-Learning/vam-marketplace-react#16]
<img width="1401" alt="Screenshot 2021-04-07 at 11 27 59 AM" src="https://user-images.githubusercontent.com/75248557/113817716-6592b700-9794-11eb-97cc-dbb4481a1bda.png">

The checkboxes are not ordered correctly, fix this

**Comment by bajaj99prashant** [comment]
solved the issue
