### ISSUE TITLE
Remove the edit option here and integrate delete subject functionality

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [Vowel-Learning/vam-marketplace-react#17]
<img width="1260" alt="Screenshot 2021-04-07 at 11 34 01 AM" src="https://user-images.githubusercontent.com/75248557/113818256-2a44b800-9795-11eb-8a67-a455d912692a.png">

Edit option here can be removed as the user can delete the subjects by just clicking on the *wrong* icon.

**Comment by bajaj99prashant** [comment]
I don't the point of the button, we can make the whole button clickable to delete. As clicking on the button triggers nothing as of now.

**Comment by sudo-NithishKarthik** [comment]
ok. Sounds reasonable, we can do it that way

**Comment by bajaj99prashant** [comment]
alright!!

**Comment by bajaj99prashant** [comment]
what api should I use for it?

**Comment by sudo-NithishKarthik** [comment]
Try it now

**Comment by bajaj99prashant** [comment]
resolved this issue!!

**Comment by sudo-NithishKarthik** [comment]
Great
