### ISSUE TITLE
Create batch integration (school)

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [Vowel-Learning/vam-marketplace-react#20]
API integration for creating batches in school

**Comment by bajaj99prashant** [comment]
How should I send time fields in the API, simply string, or is there any format?

**Comment by sudo-NithishKarthik** [comment]
Try sending ISO string, again Its really time consuming because of improper documentation of docs, but we have adjust😓

**Comment by bajaj99prashant** [comment]
Yeah they should maintain documentation.

**Comment by bajaj99prashant** [comment]
school > create-batch > create, in this API why there are two different fields starts_on and start_time.

**Comment by bajaj99prashant** [comment]
alright

**Comment by bajaj99prashant** [comment]
Hey what is pk value in course? I am sending course value as a string.

**Comment by bajaj99prashant** [comment]
Error in network tab says expected pk value.

**Comment by sudo-NithishKarthik** [comment]
pk?
Elaborate on that..post the ss

**Comment by sudo-NithishKarthik** [comment]
The id of the course should be sent,
So it should've actually been a select menu with the courses of that school and it should send the course id of the selected course

**Comment by sudo-NithishKarthik** [comment]
Change the input method to select(dropdown)

**Comment by sudo-NithishKarthik** [comment]
Create batch api is working fine now.

{
    "name": "batch1",
    "course": "7",
    "days": "Sunday,Monday",
    "start_time": "09:22 PM",
    "end_time": "09:22 PM",
    "total_sessions": "10",
    "starts_on": "2021-01-20",
    "price": "50",
    "size": "100"
}

This is the modal for sending the request

**Comment by bajaj99prashant** [comment]
The integration of create batch api is completed.

**Comment by bajaj99prashant** [comment]
resolved this issue
