### ISSUE TITLE
UI changes In add batches page

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [Vowel-Learning/vam-marketplace-react#22]
<img width="1437" alt="Screenshot 2021-04-07 at 11 53 16 AM" src="https://user-images.githubusercontent.com/75248557/113820117-ea330480-9797-11eb-97fa-11bd57cb5298.png">

remove the add session button as the user will be able to do that by clicking on **ADD THE BATCH** button.

<img width="909" alt="Screenshot 2021-04-07 at 11 54 53 AM" src="https://user-images.githubusercontent.com/75248557/113820256-13539500-9798-11eb-8e44-59f93c52bf59.png">

After the first card, which is used for adding another batch, the following cards should only show the information of existing batches, they should not be editable

**Comment by bajaj99prashant** [comment]
solved this issue.

**Comment by sudo-NithishKarthik** [comment]
Great
