### ISSUE TITLE
Modal fields incorrect placeholders

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [Vowel-Learning/vam-marketplace-react#27]
<img width="622" alt="Screenshot 2021-04-07 at 8 11 17 PM" src="https://user-images.githubusercontent.com/75248557/113885381-6c91e780-97dd-11eb-8496-7bb47d10978a.png">

Make the placeholders for each field relevant, see that last three have same 'add school'

Also, the modal should close after the user clicks on submit

**Comment by bajaj99prashant** [comment]
Alright, basically I copied the last three fields so missed it.

**Comment by sudo-NithishKarthik** [comment]
😅 no problem

**Comment by bajaj99prashant** [comment]
for now I am doing this

**Comment by sudo-NithishKarthik** [comment]
GTG

**Comment by bajaj99prashant** [comment]
resolved the issue.
